version: "3.9"

services:
  db:
    image: mysql:8
    container_name: task_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: advanced_task_manager
    ports:
      - "3307:3306"

  web:
    build: .
    container_name: task_manager_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:root123@db:3306/advanced_task_manager
